"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getXataClient = exports.XataClient = void 0;
// Generated by Xata Codegen 0.29.4. Please do not edit.
const client_1 = require("@xata.io/client");
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "mentors",
    columns: [
      { name: "name", type: "string" },
      { name: "gender", type: "string" },
      { name: "currentLocation", type: "string" },
      { name: "currentStatus", type: "string" },
      { name: "classRank", type: "int" },
      { name: "underGradInstitution", type: "string" },
      { name: "underGradDegree", type: "string" },
      { name: "undergraduateGPA", type: "float" },
      { name: "postGraduateInstitution", type: "string" },
      { name: "postGraduateDegree", type: "string" },
      { name: "programName", type: "string" },
      { name: "universityName", type: "string" },
      {
        name: "greLink",
        type: "link",
        link: { table: "greScore" },
        unique: true,
      },
      {
        name: "toeflLink",
        type: "link",
        link: { table: "toeflScore" },
        unique: true,
      },
      { name: "publicationLinks", type: "multiple" },
      { name: "experienceLinks", type: "multiple" },
      { name: "contactNumber", type: "string" },
    ],
  },
  {
    name: "greScore",
    columns: [
      { name: "Q", type: "int" },
      { name: "V", type: "int" },
      { name: "AWA", type: "int" },
    ],
    revLinks: [{ column: "greLink", table: "mentors" }],
  },
  {
    name: "toeflScore",
    columns: [
      { name: "speaking", type: "int" },
      { name: "writing", type: "int" },
      { name: "listening", type: "int" },
      { name: "reading", type: "int" },
    ],
    revLinks: [{ column: "toeflLink", table: "mentors" }],
  },
  {
    name: "publications",
    columns: [
      { name: "title", type: "string" },
      { name: "journalName", type: "string" },
      { name: "link", type: "string" },
    ],
  },
  {
    name: "professionalExperiences",
    columns: [
      { name: "title", type: "string" },
      { name: "endDate", type: "string" },
      { name: "startDate", type: "string" },
      { name: "companyName", type: "string" },
      { name: "description", type: "text" },
      { name: "awardsRecognition", type: "string" },
      { name: "numberOfPromotions", type: "int" },
    ],
  },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = (0, client_1.buildClient)();
const defaultOptions = {
  databaseURL: "https://hi-s-workspace-83b85m.us-east-1.xata.sh/db/takeleap-db",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
exports.XataClient = XataClient;
let instance = undefined;
/** @type { () => XataClient } */
const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
exports.getXataClient = getXataClient;
